### ISSUE TITLE
Error executing job with overrides:

### ISSUE THREAD

**Issue by Eddgeric** [mike9251/simswap-inference-pytorch#20]
Hello, 

I'm new to coding and machine learning and I've been having some trouble with the run_video config.
I've been trying to run it on certain videos but after about a quarter of the frames are swapped, I end up getting the following error in the cmd line and the program stops running:

Error executing job with overrides: []
Traceback (most recent call last):
  File "C:\Simswap-inference-pytorch\simswap-inference-pytorch\app.py", line 70, in main
    app.run()
  File "C:\Simswap-inference-pytorch\simswap-inference-pytorch\app.py", line 60, in run
    output = self.model(att_img)
  File "C:\Simswap-inference-pytorch\simswap-inference-pytorch\src\simswap.py", line 323, in call
    target_image = kornia.geometry.transform.warp_affine(
  File "C:\Users\user\anaconda3\envs\simswap\lib\site-packages\kornia\geometry\transform\imgwarp.py", line 203, in warp_affine
    grid = F.affine_grid(src_norm_trans_dst_norm[:, :2, :], [B, C, dsize[0], dsize[1]], align_corners=align_corners)
  File "C:\Users\user\anaconda3\envs\simswap\lib\site-packages\torch\nn\functional.py", line 4320, in affine_grid
    return torch.affine_grid_generator(theta, size, align_corners)
RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [2, 3] but got: [1, 3].

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by mike9251** [comment]
@Eddgeric hi, I need the input data you are using to reproduce the issue.
could you please upload the video on which you see this error?

**Comment by michidaeron** [comment]
> @Eddgeric hi, I need the input data you are using to reproduce the issue. could you please upload the video on which you see this error?

Getting the same error specified above without any difference.
Using this video: https://bayfiles.com/7b0a9aUcyb/xobi_mp4
using any image when running the command `python app.py --config-name=run_video.yaml` with the following config file parameters:

```
data:
  id_image: "${hydra:runtime.cwd}/demo_file/specific1.png"
  att_image: "none"
  specific_id_image: "none"
  att_video: "${hydra:runtime.cwd}/demo_file/xobi.mp4"
  output_dir: ${hydra:runtime.cwd}/output
  clean_work_dir: True

pipeline:
  face_detector_weights: "${hydra:runtime.cwd}/weights/face_detector_scrfd_10g_bnkps.onnx"
  face_id_weights: "${hydra:runtime.cwd}/weights/arcface_net.jit"
  parsing_model_weights: "${hydra:runtime.cwd}/weights/79999_iter.pth"
  simswap_weights: "${hydra:runtime.cwd}/weights/simswap_224_latest_net_G"
  gfpgan_weights: "${hydra:runtime.cwd}/weights/GFPGANv1.4_ema.pth"
  device: "cuda" #"cuda"
  crop_size: 224
  # it seems that the official 224 checkpoint works better with 'none' face alignment type
  checkpoint_type: "official_224" #"none"
  face_alignment_type: "none" #"ffhq"
  erode_mask_value: 40
  smooth_mask_value: 41
  sigma_scale_value: 1.0
  face_detector_threshold: 0.6
  specific_latent_match_threshold: 0.05
  enhance_output: True

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

```
